### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by devholic**

### CODE REVIEW

**Comment by rlatkdgus500** [comment]
Add more test code

**Comment by rlatkdgus500** [comment]
FUCK YOU AND GO SLEEP

**Comment by devholic** [comment]
What?

**Comment by rlatkdgus500** [comment]
fuck you and make test code and go sleep fucker!!!

**Comment by devholic** [comment]
Add facebook util (backend) test code in https://github.com/devholic/moon/commit/857071de9b8508841de93295d88fd25083624871

**Pull request merged**
